version: '3'
services:
  eureka-server:
    image: nexshop-eureka-server
    ports:
     - "8761:8761"
  zuul-server:
    image: nexshop-zuul-server
    depends_on:
     - eureka-server
    ports:
     - "9090:9090"
